export const PRACTICE_AREAS = [
  { id: '1', name: 'Corporate & M&A', icon: 'office-building' },
  { id: '2', name: 'Criminal Defense', icon: 'gavel' },
  { id: '3', name: 'Intellectual Property', icon: 'lightbulb-outline' },
  { id: '4', name: 'Family Law', icon: 'account-group-outline' },
  { id: '5', name: 'Personal Injury', icon: 'bandage' },
  { id: '6', name: 'Employment & Labor', icon: 'account-tie' },
  { id: '7', name: 'Real Estate', icon: 'home-city-outline' },
  { id: '8', name: 'Tax Law', icon: 'calculator' },
  { id: '9', name: 'Immigration', icon: 'airplane-takeoff' },
  { id: '10', name: 'Bankruptcy & Finance', icon: 'bank-outline' },
  { id: '11', name: 'Environmental Law', icon: 'leaf' },
  { id: '12', name: 'Civil Rights', icon: 'scale-balance' },
  { id: '13', name: 'Entertainment & Media', icon: 'movie-open-outline' },
  { id: '14', name: 'Technology & Privacy', icon: 'shield-lock-outline' },
  { id: '15', name: 'Health Law', icon: 'hospital-box-outline' },
  { id: '16', name: 'Maritime Law', icon: 'ship-wheel' },
  { id: '17', name: 'International Law', icon: 'earth' },
  { id: '18', name: 'Military Law', icon: 'shield-account' },
];
